### ISSUE TITLE
Support for Jason parser

### ISSUE THREAD

**Issue by iceniveth** [johnnyji/proper_case#27]
Phoenix 1.4 ships with Jason instead of Poison. Would be great to have support with it and has somewhat improved performance.

**Comment by antedeguemon** [comment]
It would be nice to have Jason as the default encoder. This way, a [custom encoder module](https://github.com/johnnyji/proper_case#custom-data-transform-before-encoding-with-phoenix) would not be needed for newer Phoenix projects, and the library would work out of the box. 

Just have to keep in mind that this is a breaking change and would bump the library version to `2.0.0`.

**Comment by thiamsantos** [comment]
I think that makes sense. The major point in favor of that change is that Poison v4, that is out since July 2018, don't even support the `encode_to_iodata!/1` function that is used by proper case https://github.com/johnnyji/proper_case/blob/master/lib/json_encoder.ex#L28. So right now a new project would need to explictly downgrade to be able to use it with proper_case.

IMO would makes sense to drop Poison completely and use only Jason, as Poison doesn't provide the `encode_to_iodata!/1` function.

**Comment by acco** [comment]
Took a stab at changing default parser. Not sure if @johnnyji thinks this is desirable? 

https://github.com/johnnyji/proper_case/pull/28

**Comment by johnnyji** [comment]
@acco Fantastic work 👏 Apologies for such an extended silence, merged and will release tonight!

**Comment by acco** [comment]
Great, thanks @johnnyji !!
